name: Cypress Tests
on:
  push:
    branches: [development]
  pull_request:
    branches: [development]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Code Climate test-reporter
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build
      - name: Install dependencies
        run: |
          yarn install
      - name: Cypress CI run
        run: yarn cypress:ci
      - name: Publish code coverage
        run: |
          export GIT_BRANCH="${GITHUB_HEAD_REF}"
          ./cc-test-reporter after-build -r ${{secrets.CC_TEST_REPORTER_ID}}
